### ISSUE TITLE
update PathSimAnalysis installation instructions?

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAKits#117]
PathSimAnalysis has conda packages https://www.mdanalysis.org/PathSimAnalysis/getting_started.html#conda-mamba

Should the metadata https://mdakits.mdanalysis.org/PathSimAnalysis.html#installation-instructions be updated to reflect the preferred installation or do we keep pip ?

**Comment by IAlibay** [comment]
I think usually we've been prioritizing conda vs pip so I'd +1 a change.

Longer term the metadata might need to change to have the option to have both pypi and conda-forge entries (maybe a dictionary of install instructions rather than a list?)
