### ISSUE TITLE
split MDAKit tutorial into sub-pages

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAKits#156]
The [MDAKits Tutorial](https://mdakits.mdanalysis.org/makingakit.html) contains all necessary information but feedback from users indicates that it is overwhelming in its monolithic one-page presentation. We should make it more approachable by splitting it into separate pages.

The current page can be the overview and contain a TOC with individual sections.

**Comment by IAlibay** [comment]
I'm removing the good first issue because it will involve more coordination than what I would want to subject a new contributor. I'm assigning @fiona-naughton though who will have their own views on how to achieve this.

**Comment by orbeckst** [comment]
My initial thought was that a simple refactor into separate pages would be an improvement. That can be done in the docs itself and only requires working with sphinx. 

I’m happy if @fiona-naughton wants to do it but would also happily review a PR from anyone else.
