### ISSUE TITLE
make `git clone latest` also work for install

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAKits#165]
The special case `git clone latest`
https://github.com/MDAnalysis/MDAKits/blob/8a04d6ada4eb65d2b7d0ac3527746e9d5444cbbc/utils/mdakit.py#L540-L546 would also be useful for `install` if the only way to do this is from source.

Can we enable it for `install:`, too, or would other ways be better?

**Comment by IAlibay** [comment]
This would require major reworks - it's something on my todo list, but definitely not something with a short term solution (it's targetting the test steps, and there's other code dealing with install steps).

**Comment by orbeckst** [comment]
If we don't want to use it for install, would `git clone install` be useful/necessary elsewhere? If not, we close this issue with "as not planned".

**Comment by orbeckst** [comment]
We discussed this issue at the last MDAKits meeting and we agreed that we consider "install" to mean "package install" and not a form of "source install". 

Therefore, we do not need the functionality proposed here.
