### ISSUE TITLE
install-conda-env in GH CI broken

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAKits#213]
See https://github.com/MDAnalysis/MDAKits/pull/172#issuecomment-2414884814.

The _Running installer_ steps dies with `Error: The process '/usr/bin/bash' failed with exit code 1`.

This blocks review of PR #172 and possibly affects the whole registry.

**Comment by orbeckst** [comment]
I don't know what to do here so I am pinging @IAlibay for help.

**Comment by IAlibay** [comment]
Looks like mambaforge might have just gone down, will check elsewhere in the ecosystem in the morning.

**Comment by IAlibay** [comment]
Completed with #215
