### ISSUE TITLE
Add basic mdakit contribution instructions

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/MDAKits#27]
We are now at the point where we can accept external mdakit contributions:
- [ ] update the readme to make this clearer
- [x] update the docs to have a basic set of instructions on what we expect from the yaml file and how the review process will go

**Comment by orbeckst** [comment]
@ianmkenney 's work will contribute to closing this issue, just need to do README

**Comment by orbeckst** [comment]
We have plenty of docs now.
