### ISSUE TITLE
link or embed video in web docs

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/MDAKits#86]
Link or embed the overview video https://www.youtube.com/watch?v=viCPUHkgSxg in our Making an MDAKit docs (or possibly on the front page).

**Comment by IAlibay** [comment]
more than what is done here? https://github.com/MDAnalysis/MDAKits/pull/83

**Comment by orbeckst** [comment]
Thanks for the reminder. I had seen the link in the docs and forgot about it again.

The link is not very obvious. How about actually embedding the video on the front page?

**Comment by IAlibay** [comment]
I'm not sure it's front page material? That would distract from the registry itself.

We could embed in the makingakit page though?

**Comment by orbeckst** [comment]
Ok, then let’s start with embedding it on the kits page. The current front page is pretty bare and boring, though. See also the issue about putting the registry directly on the front page. It’s not super-urgent, though. Perhaps a start is going to be to have the front page explain what kits are (our standard tag line). Am 10/1/23 um 22:04 schrieb Irfan Alibay ***@***.***>:﻿
I'm not sure it's front page material? That would distract from the registry itself.
We could embed in the makingakit page though?
